name: Node CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Puppeteer
        uses: ianwalter/puppeteer@3.0.0
        with:
          args: npm

      - name: Install and Build
        run: |
          npm install
          npm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CNAME: chrzanow.ski
